name: Exit Code
on: [workflow_dispatch]

jobs:
    build:
      name: Run Script
      runs-on: [Self-hosted, Windows, x64]
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: ./script.ps1 -ExitCode
          shell: pwsh
